name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker-registry-anmolrai.com
  DOCKER_IMAGE: java-app
  HELM_RELEASE_NAME: java-app-prod
  NAMESPACE: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    - name: Set up Helm
      uses: aws/setup-helm@v1
      with:
        version: v3.4.0

    - name: Set up kubectl
      uses: aws/setup-kubectl@v1

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG: ${{ secrets.PROD_KUBECONFIG }}
      run: |
        echo "$KUBE_CONFIG" | base64 -d > kubeconfig
        helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm-chart \
          --namespace ${{ env.NAMESPACE }} \
          --set image.repository=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }} \
          --set image.tag=${{ github.sha }} \
          --kubeconfig ./kubeconfig
        rm kubeconfig